import { ChecklistSection } from './checklistTypes';

export const DEFAULT_CHECKLIST: ChecklistSection[] = [
  {
    id: 'pre-gym',
    emoji: '🌅',
    name: 'Pre-Gym',
    items: [
      {
        id: 'wake-0430',
        name: 'Wake 4:30am',
        time: '04:30',
        layer: 'Foundation',
        purpose: 'Anchors the entire daily routine — everything depends on this wake time',
        consequence: 'If missed the whole protocol collapses',
      },
      {
        id: 'salt-lemon-water',
        name: 'Salt + lemon water',
        time: '04:30',
        layer: 'Foundation',
        purpose: 'Morning hydration and cortisol response',
        consequence: 'Energy and focus suffer within hours',
      },
      {
        id: 'outdoors-5',
        name: '5 min outdoors — stretch sunlight',
        time: '04:35',
        layer: 'Foundation',
        purpose: 'Circadian rhythm reset and cortisol anchor',
        consequence: 'Sleep quality degrades within days of missing',
      },
      {
        id: 'shower-am',
        name: 'Shower',
        time: '04:40',
        layer: 'Foundation',
        purpose: 'State reset — moves body from sleep to action',
        consequence: 'Sluggishness carries into the morning',
      },
      {
        id: 'skincare-am',
        name: 'AM skincare — Cleanser Vit C Moisturiser SPF50',
        time: '04:45',
        layer: 'Physical Product',
        purpose: 'Daily skin investment — compounds over months',
        consequence: 'Skin health and presentation decline',
      },
      {
        id: 'apple',
        name: 'Apple',
        time: '05:45',
        layer: 'Foundation',
        purpose: 'Pre-gym fuel — simple carbs before training',
        consequence: 'Performance drops without pre-gym fuel',
      },
      {
        id: 'collagen-iron',
        name: 'Collagen + Vit C + Iron',
        time: '05:45',
        layer: 'Medical',
        purpose: 'Joint repair, iron levels, immune support',
        consequence: 'Ferritin already low — missing iron supplement worsens it',
      },
    ],
  },
  {
    id: 'work-morning',
    emoji: '☀️',
    name: 'Work Morning',
    items: [
      {
        id: 'wpi-creatine-0730',
        name: 'WPI shake + creatine',
        time: '07:30',
        layer: 'Foundation',
        purpose: 'Post-gym muscle repair and creatine loading',
        consequence: 'Muscle repair window missed',
      },
      {
        id: 'eggs-avocado-0930',
        name: 'Eggs + avocado',
        time: '09:30',
        layer: 'Foundation',
        purpose: 'Hormone support and sustained energy — healthy fats critical',
        consequence: 'Hormones and energy suffer',
      },
      {
        id: 'supps-0930',
        name: 'D3 + K2 + Omega-3 + Curcumin',
        time: '09:30',
        layer: 'Medical',
        purpose: 'Vitamin D maintenance, inflammation reduction, cardiovascular support',
        consequence: 'LDL already high — Omega-3 is non-negotiable',
      },
    ],
  },
  {
    id: 'work-afternoon',
    emoji: '🥗',
    name: 'Work Afternoon',
    items: [
      {
        id: 'lunch-1230',
        name: 'Lunch — tofu + potato/veg',
        time: '12:30',
        layer: 'Foundation',
        purpose: 'Main fullness meal — protein and complex carbs',
        consequence: 'Hunger leads to poor food choices',
      },
      {
        id: 'electrolytes-walnuts-1400',
        name: 'Electrolytes + walnuts',
        time: '14:00',
        layer: 'Medical',
        purpose: 'Brain function, hydration, healthy fats',
        consequence: 'Cognitive performance drops mid-afternoon',
      },
      {
        id: 'wpi-1530',
        name: 'WPI shake',
        time: '15:30',
        layer: 'Foundation',
        purpose: 'Hunger shield — prevents overeating at dinner',
        consequence: 'Protein gap opens up',
      },
      {
        id: 'water-3l-1530',
        name: 'Water check — 3L target',
        time: '15:30',
        layer: 'Medical',
        purpose: 'Hydration is foundational to every body process',
        consequence: 'Energy, cognition, recovery all suffer',
      },
    ],
  },
  {
    id: 'after-work',
    emoji: '🏠',
    name: 'After Work',
    items: [
      {
        id: 'arrive-home-1800',
        name: 'Arrive home — 10 min rest no phone',
        time: '18:00',
        layer: 'Foundation',
        purpose: 'Nervous system reset between work and evening',
        consequence: 'Stress carries into evening routine',
      },
      {
        id: 'shower-pm-1810',
        name: 'Shower',
        time: '18:10',
        layer: 'Foundation',
        purpose: 'Energy reset — closes work state opens evening state',
        consequence: 'Evening routine quality drops',
      },
      {
        id: 'suksham-1820',
        name: 'Suksham Vyayam',
        time: '18:20',
        layer: 'Foundation',
        purpose: 'Daily mobility — hip flexors shoulders thoracic spine',
        consequence: 'Injury risk increases, mobility degrades',
      },
      {
        id: 'simran-1830',
        name: 'Waheguru simran',
        time: '18:30',
        layer: 'Inner Game',
        purpose: 'Primary nervous system regulation tool — most powerful item in the stack',
        consequence: 'Regulation capacity drops — everything above it is affected',
      },
      {
        id: 'sunlight-1845',
        name: 'Evening sunlight',
        time: '18:45',
        layer: 'Foundation',
        purpose: 'Circadian rhythm anchor for sleep',
        consequence: 'Sleep quality degrades',
      },
      {
        id: 'egg-whites-1830',
        name: 'Egg whites',
        time: '18:30',
        layer: 'Foundation',
        purpose: 'Pre-load protein before Kada Parshad',
        consequence: 'Protein target harder to hit',
      },
      {
        id: 'cook-1900',
        name: 'Cook for tomorrow',
        time: '19:00',
        layer: 'Foundation',
        purpose: 'Meal prep ensures diet compliance tomorrow',
        consequence: "Tomorrow's diet at risk",
      },
      {
        id: 'kada-1930',
        name: 'Kada Parshad',
        time: '19:30',
        layer: 'Inner Game',
        purpose: 'Daily spiritual practice — non-negotiable',
        consequence: 'Spiritual foundation weakens',
      },
      {
        id: 'read-10-2000',
        name: 'Read 10 pages',
        time: '20:00',
        layer: 'Presence',
        purpose: 'Intellect layer — daily input',
        consequence: 'Mind stagnates without daily input',
      },
      {
        id: 'skincare-pm-2000',
        name: 'PM skincare — Cleanser Retinol Moisturiser',
        time: '20:00',
        layer: 'Physical Product',
        purpose: 'Skin repair during sleep — retinol works overnight',
        consequence: 'Skin investment missed',
      },
      {
        id: 'read-aloud-2015',
        name: 'Read aloud',
        time: '20:15',
        layer: 'Presence',
        purpose: 'Voice training — reduces filler words builds confidence',
        consequence: 'Voice development stalls',
      },
    ],
  },
  {
    id: 'bedtime',
    emoji: '😴',
    name: 'Bedtime',
    items: [
      {
        id: 'no-screens-2000',
        name: 'No screens from 8:00pm',
        time: '20:00',
        layer: 'Sleep',
        purpose: 'Blue light blocks melatonin — screens are the primary sleep killer',
        consequence: 'Sleep onset delayed, quality drops',
      },
      {
        id: 'magnesium-2015',
        name: 'Magnesium glycinate',
        time: '20:15',
        layer: 'Medical',
        purpose: 'Sleep quality and muscle recovery',
        consequence: 'Sleep quality drops without it',
      },
      {
        id: 'in-bed-2030',
        name: 'In bed by 8:30pm',
        time: '20:30',
        layer: 'Sleep',
        purpose: '4:30am wake only works with 8:30pm bedtime — non-negotiable',
        consequence: 'Entire morning protocol collapses',
      },
    ],
  },
];
